CREATE PLUGGABLE DATABASE plsql_class2024db
  2  ADMIN USER PA_plsqlauca IDENTIFIED BY 1234
  3  FILE_NAME_CONVERT=('C:\USERS\ORADATA\ORCL\PDBSEED\',
  4                     'C:\USERS\ORADATA\ORCL\PDBSEED\newpdb\');
CREATE PLUGGABLE DATABASE FA_TO_DELETE_PDB
  2  ADMIN USER PA_plsqlauca IDENTIFIED BY 1234
  3  FILE_NAME_CONVERT=('C:\USERS\ORADATA\ORCL\PDBSEED\',
  4                     'C:\USERS\ORADATA\ORCL\PDBSEED\newpdb1\');
 ALTER PLUGGABLE DATABASE FA_TO_DELETE_PDB UNPLUG INTO 'C:\USERS\ORADATA\ORCL PDB_DEMO.XML';
DROP PLUGGABLE DATABASE FA_TO_DELETE_PDB INCLUDING DATAFILES;

CREATE USER pacience IDENTIFIED BY 1234;
GRANT ALL PRIVILEGES TO pacience;
BEGIN
  2  DBMS_XDB_CONFIG.SETHTTPPORT(8080);
  3  DBMS_XDB_CONFIG.SETHTTPSPORT(5500);
  4  END;
  5  /
SELECT DBMS_XDB_CONFIG.GETHTTPPORT() AS HTTP_PORT,
  2         DBMS_XDB_CONFIG.GETHTTPSPORT() AS HTTPS_PORT
  3  FROM DUAL;
